FROM swaggerapi/swagger-ui

# Create a directory for your API definitions
RUN mkdir -p /usr/share/nginx/html/api

# Copy your API definition files into the container
COPY ./openapi.yaml /usr/share/nginx/html/api/swagger.yaml
#COPY parameters/petId.yaml /usr/share/nginx/html/api/schemas/petId.yaml
#COPY paths/pets.yaml /usr/share/nginx/html/api/schemas/pets.yaml
#COPY responses/UnexpectedError.yaml /usr/share/nginx/html/api/schemas/UnexpectedError.yaml
COPY ./schemas/schemas.yaml /usr/share/nginx/html/api/schemas/schemas.yaml

# Set environment variables to point to your main API definition file
ENV SWAGGER_JSON=/usr/share/nginx/html/api/swagger.yaml
