openapi: "3.0.0"
info:
  description: "# UA System API - Overview\n\n## Introduction\n\nThis document serves as a comprehensive guide to help users interact with the various methods of the UA System API. The UA System API is designed to facilitate the management and operation of unmanned aerial systems (UAS) by providing access to essential data and functionalities.\n\n## Getting Started\n\nTo get started with the UA System API, follow these steps to ensure a smooth integration and usage experience.\n\n### Using The API\n\nThe UA System API allows you to access and manage data related to unmanned aerial systems. This includes functionalities such as retrieving UAS data, managing equipment, and overseeing operational tasks. The API is built using RESTful web services, ensuring it is robust, scalable, and easy to use.\n\n## Uptime & Planned Outages\n\nThe UA System API aims to maintain high availability and reliability. Any planned outages or maintenance windows will be communicated in advance to ensure minimal disruption. Real-time status updates and planned maintenance schedules can be found on our status page.\n\n### Rate Limits\n\nTo ensure fair usage and system stability, the UA System API enforces rate limits on the number of requests a user can make. The standard rate limit is 70 requests per minute. If this limit is exceeded, users will receive a `429 Too Many Requests` response, with a `Retry-After` header indicating when they can make the next request.\n\n## Contact Us\n\nFor any questions, support requests, or feedback regarding the UA System API, please contact us through the following channels:\n\n- **Email**: support@example.com\n- **Phone**: +1-800-555-1234\n- **Support Portal**: [Contact Support](https://example.com/support)\n\nWe are committed to providing timely and helpful assistance to ensure a positive experience with the UA System API."
  contact:
    email: "jakub.manak@unicornuniversity.net"
    url: "https://example.com/contact"
  version: 0.1.0
  title: "UA System API"
tags:
  - name: "aircraft"
    description: "UA operations."
  - name: "transmitter"
    description: "Transmitter operations related to UA."
  - name: "transponder"
    description: "Transponder operations related to UA."
  - name: "sensor"
    description: "Sensor operations."
  - name: "product"
    description: "Product operations."
paths:
  /ump/aircraft:
    $ref: "./paths/paths.yaml#/paths/listAircraft"
  /ump/aircraft/{aircraft_id}:
    $ref: "./paths/paths.yaml#/paths/aircraftId"
  /ump/aircraft/{aircraft_id}/transmitters:
    $ref: "./paths/paths.yaml#/paths/aircraftIdTransmitter"
  /ump/aircraft/{aircraft_id}/transponders/{transponder_id}:
    $ref: "./paths/paths.yaml#/paths/aircraftIdTransponder"
  /ump/sensors:
    $ref: "./paths/paths.yaml#/paths/listSensors"
  /ump/sensors/{sensor_id}:
    $ref: "./paths/paths.yaml#/paths/sensorId"

  /ump/products:
    $ref: "./paths/paths.yaml#/paths/listProducts"
  /ump/products/{product_id}:
    $ref: "./paths/paths.yaml#/paths/productId"


components:
  schemas:
    error:
      $ref: "./schemas/schemas.yaml#/schemas/error"
    aircraft:
      $ref: "./schemas/schemas.yaml#/schemas/aircraft"
    sensor:
      $ref: "./schemas/schemas.yaml#/schemas/sensor"
    product:
      $ref: "./schemas/schemas.yaml#/schemas/product"
    transmitter:
      $ref: "./schemas/schemas.yaml#/schemas/transmitter"
    transponder:
      $ref: "./schemas/schemas.yaml#/schemas/transmitter"

  requestBodies:
    aircraftIdBody:
      $ref: "./schemas/requestBodies.yaml#/requestBodies/aircraftIdBody"

  parameters:
    aircraftIdParam:
      $ref: "./parameters/aircraftParameters.yaml#/parameters/aircraftIdParam"
    typeUaParam:
      $ref: "./parameters/aircraftParameters.yaml#/parameters/typeUaParam"
    modelUaParam:
      $ref: "./parameters/aircraftParameters.yaml#/parameters/modelUaParam"
    statusUaParam:
      $ref: "./parameters/aircraftParameters.yaml#/parameters/statusUaParam"
    lastFlightUaParam:
      $ref: "./parameters/aircraftParameters.yaml#/parameters/lastFlightUaParam"
    registrationNumUaParam:
      $ref: "./parameters/aircraftParameters.yaml#/parameters/registrationNumUaParam"
    dateCreatedUaParam:
      $ref: "./parameters/aircraftParameters.yaml#/parameters/dateCreatedUaParam"
    dateModifiedUaParam:
      $ref: "./parameters/aircraftParameters.yaml#/parameters/dateModifiedUaParam"
    pageUaParam:
      $ref: "./parameters/aircraftParameters.yaml#/parameters/pageUaParam"
    limitUaParam:
      $ref: "./parameters/aircraftParameters.yaml#/parameters/limitUaParam"
    locationUaParam:
      $ref: "./parameters/aircraftParameters.yaml#/parameters/locationUaParam"

  responses:
    SuccessAircraft:
      $ref: "./responses/responses.yaml#/responses/SuccessAircraft"
    SuccessAircraftId:
      $ref: "./responses/responses.yaml#/responses/SuccessAircraftId"
    Deleted:
      $ref: "./responses/responses.yaml#/responses/Deleted"
  securitySchemes: { }
servers:
  - url: "/ump/v1/"